
CREATE TABLE IF NOT EXISTS TB_USER(
   USER_ID VARCHAR(32) NOT NULL,
   NAME VARCHAR(100) NOT NULL,
   PASSWORD VARCHAR(100) NOT NULL,
   BIRTHDAY DATE,
   MAIL VARCHAR(100),
   STATUS VARCHAR(10) NOT NULL,
   PRIMARY KEY (USER_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS TB_USER_ADDRESS(
   USER_ID VARCHAR(32) NOT NULL,
   ADDRESS_ID VARCHAR(32) NOT NULL,
   ADDRESS VARCHAR(2000) NOT NULL,
   ADD_DATE DATE,
   IS_DEFAULT TINYINT(1) NOT NULL,
   PRIMARY KEY (ADDRESS_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;